### ISSUE TITLE
首次运行的错误信息

### ISSUE THREAD

**Issue by hzeasy** [metercai/SimpleSDXL#11]
首先感谢制作分享，但上手不易。
![149567ce9b4af5e4d2191271f7c3fc3](https://github.com/metercai/SimpleSDXL/assets/136664755/5e35831b-7034-4c76-8de5-a24bd9a8a5b1)
用run运行需要从抱脸下载，改从sync_models运行出现错误提示（如图），国内用户必然是网络不便才有使用它的需求，不然原版是最好的选择。所以建议中国化就彻底一点。

**Comment by metercai** [comment]
有两个一键安装包，含"in"的是从国内魔搭社区下载模型文件。如图示：<img width="1198" src="https://github.com/metercai/SimpleSDXL/assets/5652458/d4e2281c-a110-4d22-a576-b70871828771">

用"in"包而出现抱抱脸下载，应该是因为从魔搭社区下载失败后直接进入fooocus的原版下载流程了。先确保魔搭社区可访问才行。

**Comment by hzeasy** [comment]
> 用"in"包而出现抱抱脸下载，应该是因为从魔搭社区下载失败后直接进入fooocus的原版下载流程了。先确保魔搭社区可访问才行。

确定用的是in包，也能开魔搭社区网站，但还是从抱脸下载
![d824ec955ee8544c6a5391200c79411](https://github.com/metercai/SimpleSDXL/assets/136664755/778df5d3-afdf-430c-b373-e122316c14d2)
我是很想把这个推广给没有梯子的朋友使用，但一波操作下来还是实现不了。

**Comment by metercai** [comment]
我再从源头捋一下，看看如何改进

**Comment by metercai** [comment]
启动流程重新捋了一遍，启动器也完全瘦身不到100M，下载源全部更新为国内源。

**Comment by hzeasy** [comment]
操作反馈：
从介绍页下载SimpleSDXL_win64_in 文件，解压SimpleSDXL_win64_in得到如图1所示的目录，进入目录运行RUN得到图2提示：
![a18214f7332c5b7d7b2124e54c17119](https://github.com/metercai/SimpleSDXL/assets/136664755/8bf2fd4d-e207-4dba-8795-bcce0527fa4a)

![7ccf34d8626ab29ca104f533044f3b6](https://github.com/metercai/SimpleSDXL/assets/136664755/a4a93d24-1a1d-445e-afc0-94746106bec4)

是否我错过了哪些步骤？

**Comment by metercai** [comment]
从提示信息看，还是本地网络环境有问题。估计有可能是受你的科学上网影响，关掉，直接用国内网络试试。
![image](https://github.com/metercai/SimpleSDXL/assets/5652458/e36e057f-9c17-41da-8e72-1bc8e4ed2c72)
另外，如果重新从头安装，只需下载SimpleSDXL_win64_in  这一个启动器包就可以了。昨天又从新优化了一版，可以删除旧的文件，重新下载安装：https://gitee.com/metercai/SimpleSDXL/releases/download/win64/SimpleSDXL_win64_in.exe

**Comment by metercai** [comment]
不客气，能用就好。从魔搭社区同步模型确实比较慢，但可以一次性同步所有模型。SimpleSDXL新的一键包为了方便第一次安装，采用另外一个源按需下载，不用完全从魔搭社区同步就可以出图了。
