### ISSUE TITLE
关于启动后等待

### ISSUE THREAD

**Issue by huangxin1745** [metercai/SimpleSDXL#18]
启动后显示Installing requirements会进入很长一段时间的等待才能进入Fooocus，后台显示找不到models_info.json和albedobaseXL_v13.safetensors模型，我之前用的是原版的Fooocus，模型路径我改成了webui的模型文件夹路径，安装了SimpleSDXL我替换掉了原来的config.txt文件，我不知道是否是这个原因造成的，如果是的话那我不是要重新拷贝一份模型文件到Fooocus文件夹下？

**Comment by metercai** [comment]
正常情况下不需要，可以贴一下后台报错日志和config.txt

**Comment by huangxin1745** [comment]
Already up-to-date
Update succeeded.
[System ARGV] ['.\\SimpleSDXL\\entry_with_update.py']
Loaded preset: D:\Fooocus_win64_2-1-831\SimpleSDXL\presets\default.json
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.856
SimpleSDXL version: v20231230.1c557b1
Installing requirements
启动后等待

**Comment by huangxin1745** [comment]
[TokenDID] Generated local_did: "FUJT7mQWfZfna46f8asgkXN3dpyFfsbh6"
[TokenDID] Loaded 1 DIDs from root_path.
[ModelInfo] Update model info file [D:\Fooocus_win64_2-1-831\SimpleSDXL\models\models_info.json] failed!
[WinError 2] 系统找不到指定的文件。: 'D:\\Fooocus_win64_2-1-831\\SimpleSDXL\\models\\checkpoints\\albedobaseXL_v13.safetensors'
[Gallery] Refresh_output_list: loaded 8 images_lists.
Total VRAM 16380 MB, total RAM 32503 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Refiner unloaded.
[Topbar] Reset_context: preset=default-->default, theme=dark-->dark
[Topbar] The model file in preset is not local, ready to download.
[Gallery] Parse_html_log: loaded 20 image_infos of 23-12-31.
[Gallery] Refresh_images_list: loaded 20 image_items of 23-12-31.
model_type EPS
UNet ADM Dimension 2816
[Gallery] Selected_gallery: selected index 0 of 23-12-31 images_list.
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: D:\novelai-webui\novelai-webui-aki-v2\models\Stable-diffusion\SDXL\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\novelai-webui\novelai-webui-aki-v2\models\Stable-diffusion\SDXL\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [D:\novelai-webui\novelai-webui-aki-v2\models\Lora\SDXL\sd_xl_offset_example-lora_1.0.safetensors] for UNet [D:\novelai-webui\novelai-webui-aki-v2\models\Stable-diffusion\SDXL\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.38 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
启动成功后

**Comment by huangxin1745** [comment]
{
    "path_checkpoints": "D:\\novelai-webui\\novelai-webui-aki-v2\\models\\Stable-diffusion\\SDXL",
    "path_loras": "D:\\novelai-webui\\novelai-webui-aki-v2\\models\\Lora\\SDXL",
    "path_embeddings": "D:\\Fooocus_win64_2-1-831\\Fooocus\\models\\embeddings",
    "path_vae_approx": "D:\\Fooocus_win64_2-1-831\\Fooocus\\models\\vae_approx",
    "path_upscale_models": "D:\\Fooocus_win64_2-1-831\\Fooocus\\models\\upscale_models",
    "path_inpaint": "D:\\Fooocus_win64_2-1-831\\Fooocus\\models\\inpaint",
    "path_controlnet": "D:\\Fooocus_win64_2-1-831\\Fooocus\\models\\controlnet",
    "path_clip_vision": "D:\\Fooocus_win64_2-1-831\\Fooocus\\models\\clip_vision",
    "path_fooocus_expansion": "D:\\Fooocus_win64_2-1-831\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
    "path_outputs": "D:\\Fooocus_win64_2-1-831\\Fooocus\\outputs"
}

**Comment by metercai** [comment]
1，第一次启动后等待是在安装新增组件，二次启动就应该不会了。
2，路径兼容性问题已修复，可以再试试看。

**Comment by metercai** [comment]
启动后等待是因为组件版本号不一致导致的重复安装，目前已解决。
