### ISSUE TITLE
第一次运行模型下载很慢

### ISSUE THREAD

**Issue by dhlsam** [metercai/SimpleSDXL#19]
linux环境搭建，但是第一次运行国内环境安装好以后自动下载模型的速度很慢
已经好几天了还在下base模型，我看到enhanced文件夹里的hub host是腾讯云的ip，如何可以设置直接走huggingface下载

**Comment by metercai** [comment]
更新了版本，开启根据接入位置自动选择下载源的能力，同时提供启动参数 `--location CN` 或 `--location EN` 强制指定接入位置。重构的时候有预留，现在正好把它搞完😄

**Comment by dhlsam** [comment]
> 更新了版本，开启根据接入位置自动选择下载源的能力，同时提供启动参数 `--location CN` 或 `--location EN` 强制指定接入位置。重构的时候有预留，现在正好把它搞完😄
我用docker 装的 是不是加入location参数就可以解决了
command: python entry_with_update.py --listen 0.0.0.0 --port 8889 --location EN

**Comment by metercai** [comment]
是这样的，如果OK的话，回复一下，这个事算是搞定了😄

**Comment by dhlsam** [comment]
> 是这样的，如果OK的话，回复一下，这个事算是搞定了😄

感谢 搞定 下载速度上来了，就是语言自动又变成英文了 ，是不是添加--location EN --language cn 可以切换回中文，但下载还是海外路线

**Comment by metercai** [comment]
对的，国内接入缺省中文和国内源，海外接入缺省英文和国外源，你这种情况需要自己配置了😄
