### ISSUE TITLE
脸书的翻译模型没有加入后端的模型管理模块

### ISSUE THREAD

**Issue by siriume** [metercai/SimpleSDXL#3]
**Describe the problem**
脸书的翻译模型没有加入后端的模型管理模块, 会导致低显存时出现oom情况

**Full Console Log**
None.

**Comment by metercai** [comment]
这个预计得到最后才能做了，算力云化是个难啃的骨头

**Comment by metercai** [comment]
现在已经同步支持模型翻译和接口翻译，低显存可以选择接口翻译了。
