### ISSUE TITLE
how can I share my Stablediffusion Automatic 1111 checkpoints folder with Fooocus ?

### ISSUE THREAD

**Issue by eflin1** [metercai/SimpleSDXL#31]
**Is your feature request related to a problem? Please describe.**

**Describe the idea you'd like**

**Comment by metercai** [comment]
Configure it in config.txt as same as Fooocus

**Comment by LiJT** [comment]
> Configure it in config.txt as same as Fooocus

但是大佬，现在这个版本，他没法读取子目录呀，我的automatic 1111模型目录为每个画风的模型都分好了类并且放在根目录下面不同的文件夹下，但是现在无法读取，依然只能放在根目录才能识别，否则就会重新下载，很是麻烦

**Comment by metercai** [comment]
支持子目录下模型文件的读取啊
