### ISSUE TITLE
预设可以分享，添加，删除(Make presets can be shared, imported and removed)

### ISSUE THREAD

**Issue by power88** [metercai/SimpleSDXL#4]
**Is your feature request related to a problem? Please describe.**
并不是，这个只是在使用源项目fooocus制作json预设的时候想到的
Nope. This idea is suddenly thought when creating a json preset in Fooocus.

**Describe the idea you'd like**
如标题所示，在顶部预设切换栏旁边添加一个预设编辑器的按钮，之后弹出一个窗口，里面可以删除，保存（将当前界面的设置存储为一个json文件，并与源项目fooocus兼容），导入，导出（以压缩包格式导出json文件和模型，或者是以json格式导出预设文件），删除（添加一个复选框，内容为“随模型一起删除”）预设.

As shown in the title, add a button called "Preset Manager" which shows a window after clicking it. In this window, there's a list of presets, which can save (as a json file which compatible with Fooocus), import, export (as a raw json file or embedded zip file with models) and remove (with model by clicking a checkbox) a preset.

**Comment by metercai** [comment]
制作发布预置包是个偏小众的需求，而且没必要挤在Topbar上。最新更新的“生成参数查看”功能可以体验一下，后续有计划将生成参数嵌入生成图片，置入预置包标识。这样可以将嵌入参数的图片作为介质，把预置包的便捷能力充分发挥出来。

**Comment by power88** [comment]
当然可以，那就希望把预设信息（包括下载链接等），model hash存储到图片中，这样更加方便

**Comment by metercai** [comment]
新版本增加了预置包生成，可以体验一下。
