### ISSUE TITLE
提示token_user.pem failed Bad decrypt

### ISSUE THREAD

**Issue by Shun-Ge** [metercai/SimpleSDXL#42]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

每次开机重新启动项目，都会提示Load user private key file [/code/SimpleSDXL/.token_user.pem] failed
Bad decrypt. Incorrect password?，最后程序终止，如果删掉这个文件就可以正常运行了，请问应该怎么做才能避免这样的情况发生

### Steps to reproduce the problem

python entry_with_update.py --share

### What should have happened?

继续执行

### What browsers do you use to access Fooocus?

Microsoft Edge

### Where are you running Fooocus?

Cloud (other)

### What operating system are you using?

Ubuntu

### Console logs

```Shell
Load user private key file [/code/SimpleSDXL/.token_user.pem] failed
Bad decrypt. Incorrect password?
Traceback (most recent call last):
  File "/code/SimpleSDXL/entry_with_update.py", line 86, in <module>
    from launch import *
  File "/code/SimpleSDXL/launch.py", line 105, in <module>
    token_did.init_local_did(f'SimpleSDXL_User')
  File "/code/SimpleSDXL/enhanced/token_did.py", line 52, in init_local_did
    prikey_user.private_bytes(  encoding=serialization.Encoding.Raw,
AttributeError: 'str' object has no attribute 'private_bytes'
```

**Comment by metercai** [comment]
你用的云环境？每次运行的环境每次都会变化吗？

**Comment by Shun-Ge** [comment]
> 你用的云环境？每次运行的环境每次都会变化吗？

是有一些变化
