### ISSUE TITLE
[Feature Request]: Only change [output_format] when a preset json contains a [default_output_format] entry

### ISSUE THREAD

**Issue by steppres** [metercai/SimpleSDXL#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Image output file format (png, jpeg etc...) defaults to png when changing presets when [defautl_output_format] is missing from a preset package json.

I propose [output_format] only change when [defautl_output_format] is included inside a preset json.

(Apologies for using English to submit this 🙃)

### Proposed workflow

1. Launch SimpleSDXL with "default_output_format": "jpeg" in config.txt
2. Click preset in topbar
3. output_format only changes from jpeg if preset contains [defautl_output_format]

**Comment by metercai** [comment]
It will be resolved in the next version
