### ISSUE TITLE
[Feature Request]: 切换预设时可以不清空提示词吗？

### ISSUE THREAD

**Issue by skywolf123** [metercai/SimpleSDXL#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

每次我切换预设，都会清空提示词，但是我想看下同提示词在不同预设的效果，或者用错了预设，就很麻烦，老是要重新输入，能不能在切换预设时提示词不被清空啊

### Proposed workflow

1. 切换预设
2. 不要清空提示词

**Comment by metercai** [comment]
下个版本解决

**Comment by metercai** [comment]
在测试版上已经解决，可以验证测试。后续会升级到正式版
