### ISSUE TITLE
SIMPLESDXL2_WIN一点击运行就报错[Bug]: 无法使用

### ISSUE THREAD

**Issue by 418559154** [metercai/SimpleSDXL#50]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

<img width="934" alt="fooocus报错" src="https://github.com/user-attachments/assets/f37922f9-9436-444d-9b57-a444a18f07bf">
点击运行run_SimpleSDXL.bat后输入一个cat提示词运行就报错

### Steps to reproduce the problem

复制安装包，正常启动就会有问题，无报错

### What should have happened?

正常应该可以运行程序

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### Console logs

```Shell
Ready to checkout SimpleSDXL
SimpleSDXL: Already up-to-date, 130b193
[System ARGV] ['SimpleSDXL\\entry_with_update.py']
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.4.3
Comfy version: 1281f93
SimpleSDXL version: v20240630.130b193
Uninstall simpleai_base 0.3.16
Install simpleai_base 0.3.15
Checking ...
[SimpleAI] GPU: NVIDIA GeForce RTX 4090, RAM: 130946MB, SWAP: 19456MB, VRAM: 24564MB, DiskFree: 850926MB
[SimpleAI] local_did/本地身份ID: 39H5q6YjCuWUBSc2FWtGAn4iTXZk
Load config data from H:\SimpleSDXL2_win\SimpleSDXL\config.txt.
Loaded preset: H:\SimpleSDXL2_win\SimpleSDXL\presets\default.json
Total VRAM 24563 MB, total RAM 130947 MB
xformers version: 0.0.26
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
VAE dtype: torch.bfloat16
[Cleanup] Attempting to delete content of temp dir C:\Users\Administrator\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Using xformers cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
[Wildcards] Refresh and Load 27/27 wildcards: animal, bodytypes, buildings, chairs, color, containers, coverings, flora, flower, focus, foods, hairstyles, jobs, materials, minilocations, moods, nationality, objects, objectstohold, outfits, patterns, poses, rpg, shotsizes, space, timeperiods, vehicles.
[OneButtonPrompt] The customized module:OneButtonPrompt is initializing ...
IMPORTANT: You are using gradio version 3.41.2, however version 4.29.0 is available, please upgrade.
--------
Running on local URL:  http://192.168.1.5:8186

To create a public link, set `share=True` in `launch()`.
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Base model loaded: H:\SimpleSDXL2_win\SimpleSDXL\models\checkpoints\juggernaut-X-RunDiffusion-NSFW.safetensors
VAE loaded: None
Request to load LoRAs [('sd_xl_offset_example-lora_1.0.safetensors', 0.1)] for model [H:\SimpleSDXL2_win\SimpleSDXL\models\checkpoints\juggernaut-X-RunDiffusion-NSFW.safetensors].
Loaded LoRA [H:\SimpleSDXL2_win\SimpleSDXL\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [H:\SimpleSDXL2_win\SimpleSDXL\models\checkpoints\juggernaut-X-RunDiffusion-NSFW.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 1.51 seconds
Started worker with PID 6036
App started successful. Use the app with http://192.168.1.5:8186/ or 192.168.1.5:8186
```

### Additional information

无

**Comment by 418559154** [comment]
我的cuda:
C:\Users\Administrator>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

C:\Users\Administrator>

**Comment by metercai** [comment]
> ### Checklist
> * [ ]  The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
> * [ ]  The issue exists on a clean installation of Fooocus
> * [x]  The issue exists in the current version of Fooocus
> * [x]  The issue has not been reported before recently
> * [ ]  The issue has been reported before but has not been fixed yet
> 
> ### What happened?
> <img alt="fooocus报错" width="934" src="https://private-user-images.githubusercontent.com/175458640/348438932-f37922f9-9436-444d-9b57-a444a18f07bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4OTA2NTQsIm5iZiI6MTcyMDg5MDM1NCwicGF0aCI6Ii8xNzU0NTg2NDAvMzQ4NDM4OTMyLWYzNzkyMmY5LTk0MzYtNDQ0ZC05YjU3LWE0NDRhMThmMDdiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxNzA1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzdhYzU4YTVjZTk3MmUxNWYxYmUxNTc4MDAyMzQwMTJjZmNkZmVjNGEzNzc4YTYwYjE4MzNiNDI0NmI3Njc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DFdTq5XSO3p1nzg8QgyvDA9Kk5i0gAReqkIak-HLQH8"> 点击运行run_SimpleSDXL.bat后输入一个cat提示词运行就报错
> ### Steps to reproduce the problem
> 复制安装包，正常启动就会有问题，无报错
> 
> ### What should have happened?
> 正常应该可以运行程序
> 
> ### What browsers do you use to access Fooocus?
> Google Chrome
> 
> ### Where are you running Fooocus?
> Locally
> 
> ### What operating system are you using?
> _No response_
> 
> ### Console logs
> ```shell
> Ready to checkout SimpleSDXL
> SimpleSDXL: Already up-to-date, 130b193
> [System ARGV] ['SimpleSDXL\\entry_with_update.py']
> Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
> Fooocus version: 2.4.3
> Comfy version: 1281f93
> SimpleSDXL version: v20240630.130b193
> Uninstall simpleai_base 0.3.16
> Install simpleai_base 0.3.15
> Checking ...
> [SimpleAI] GPU: NVIDIA GeForce RTX 4090, RAM: 130946MB, SWAP: 19456MB, VRAM: 24564MB, DiskFree: 850926MB
> [SimpleAI] local_did/本地身份ID: 39H5q6YjCuWUBSc2FWtGAn4iTXZk
> Load config data from H:\SimpleSDXL2_win\SimpleSDXL\config.txt.
> Loaded preset: H:\SimpleSDXL2_win\SimpleSDXL\presets\default.json
> Total VRAM 24563 MB, total RAM 130947 MB
> xformers version: 0.0.26
> Set vram state to: NORMAL_VRAM
> Always offload VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4090 : native
> VAE dtype: torch.bfloat16
> [Cleanup] Attempting to delete content of temp dir C:\Users\Administrator\AppData\Local\Temp\fooocus
> [Cleanup] Cleanup successful
> Using xformers cross attention
> Refiner unloaded.
> model_type EPS
> UNet ADM Dimension 2816
> [Wildcards] Refresh and Load 27/27 wildcards: animal, bodytypes, buildings, chairs, color, containers, coverings, flora, flower, focus, foods, hairstyles, jobs, materials, minilocations, moods, nationality, objects, objectstohold, outfits, patterns, poses, rpg, shotsizes, space, timeperiods, vehicles.
> [OneButtonPrompt] The customized module:OneButtonPrompt is initializing ...
> IMPORTANT: You are using gradio version 3.41.2, however version 4.29.0 is available, please upgrade.
> --------
> Running on local URL:  http://192.168.1.5:8186
> 
> To create a public link, set `share=True` in `launch()`.
> Using xformers attention in VAE
> Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
> Using xformers attention in VAE
> extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
> left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
> Base model loaded: H:\SimpleSDXL2_win\SimpleSDXL\models\checkpoints\juggernaut-X-RunDiffusion-NSFW.safetensors
> VAE loaded: None
> Request to load LoRAs [('sd_xl_offset_example-lora_1.0.safetensors', 0.1)] for model [H:\SimpleSDXL2_win\SimpleSDXL\models\checkpoints\juggernaut-X-RunDiffusion-NSFW.safetensors].
> Loaded LoRA [H:\SimpleSDXL2_win\SimpleSDXL\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [H:\SimpleSDXL2_win\SimpleSDXL\models\checkpoints\juggernaut-X-RunDiffusion-NSFW.safetensors] with 788 keys at weight 0.1.
> Fooocus V2 Expansion: Vocab with 642 words.
> Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
> Requested to load SDXLClipModel
> Requested to load GPT2LMHeadModel
> Loading 2 new models
> [Fooocus Model Management] Moving model(s) has taken 1.51 seconds
> Started worker with PID 6036
> App started successful. Use the app with http://192.168.1.5:8186/ or 192.168.1.5:8186
> ```
> 
> ### Additional information
> 无

后台显示启动成功，但没有看到任何报错信息呢？
