### ISSUE TITLE
[Feature Request]: 集成fastapi

### ISSUE THREAD

**Issue by prog-ape** [metercai/SimpleSDXL#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

大佬，能否集成类似fooocus-api的接口功能，原始的api调用实在太痛苦了

### Proposed workflow

集成类似fooocus-api的接口功能

**Comment by metercai** [comment]
为啥要集成它？

**Comment by xinjiguaike** [comment]
这个需求其实是个刚需，方便其他系统集成，出图的界面一般外部系统都会自己设计，主要是想用这个项目的后端出图能力；所以能对外提供封装好的api接口对其他系统集成来说就方便很多了

**Comment by metercai** [comment]
但这个不是项目本身的诉求...
