### ISSUE TITLE
[Feature Request]: 无缝图案需求

### ISSUE THREAD

**Issue by cannon-fodder-art** [metercai/SimpleSDXL#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

希望大佬能够增加无缝图案控制器，可用于生成无缝图案，适合用于一些需要重复平铺的场景。
asymmetric-tiling-sd-webui是一个开源的webui无缝图案插件，可借鉴。

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by metercai** [comment]
已完成上线
