### ISSUE TITLE
[Feature Request]: BitsandBytes for Flux

### ISSUE THREAD

**Issue by wangfeng35** [metercai/SimpleSDXL#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

[lllyasviel](https://github.com/lllyasviel)大佬量化了个新的flux模型：[flux1-dev-bnb-nf4.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4.safetensors)，生图速度比comfyui的快了一倍。

细节见：https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981

希望能考虑跟进下这个新方法。

### Proposed workflow

1. flux生图后端更新
2. 采用flux1-dev-bnb-nf4.safetensors模型

**Comment by metercai** [comment]
测试版上已经有了啊
