### ISSUE TITLE
[Bug]:提示虚拟内存容量过小，今天突然出现的，没有做任何改动。

### ISSUE THREAD

**Issue by kalvinses** [metercai/SimpleSDXL#59]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

昨天还能正常启动的，今天打开的时候突然提示如下：
----------------
SimpleSDXL: Already up-to-date, feea3f1
[System ARGV] ['SimpleSDXL\\entry_with_update.py', '--models-root', '../../SimpleModels', '--output-path', '../../outputs']
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.5.2
Comfy version: 897325c
SimpleSDXL version: v20240731.feea3f1
Checking ...
[SimpleAI] GPU: NVIDIA GeForce RTX 4070, RAM: 32477MB, SWAP: 5632MB, VRAM: 12282MB, DiskFree: 383415MB
The total virtual memory capacity of the system is too small, which will affect the loading and computing efficiency of the model. Please expand the total virtual memory capacity of the system to be greater than 40G.
系统虚拟内存总容量过小，会影响模型的加载与计算效率，请扩充系统虚拟内存总容量大于40G。
All done.
请按任意键继续. . .
----------------------
我配置是4070 12G，32G内存，amd 7500的处理器，前几次都能正常打开，今天不管怎么试都会提示这个错误，没有别的操作，就是双击run_SImpleSDXL.bat运行的。

### Steps to reproduce the problem

1、打开D:\SimpleAI\SimpleSDXL2_win文件夹，
2、双击run_SImpleSDXL.bat运行

### What should have happened?

之前可以正常打开并且生成图片也都是正常的

### What browsers do you use to access Fooocus?

Microsoft Edge

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows11

### Console logs

```Shell
SimpleSDXL: Already up-to-date, feea3f1
[System ARGV] ['SimpleSDXL\\entry_with_update.py', '--models-root', '../../SimpleModels', '--output-path', '../../outputs']
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.5.2
Comfy version: 897325c
SimpleSDXL version: v20240731.feea3f1
Checking ...
[SimpleAI] GPU: NVIDIA GeForce RTX 4070, RAM: 32477MB, SWAP: 5632MB, VRAM: 12282MB, DiskFree: 383343MB
The total virtual memory capacity of the system is too small, which will affect the loading and computing efficiency of the model. Please expand the total virtual memory capacity of the system to be greater than 40G.
系统虚拟内存总容量过小，会影响模型的加载与计算效率，请扩充系统虚拟内存总容量大于40G。
All done.
请按任意键继续. . .
```

### Additional information

之前是正常的，自己添加了一个ponyreal的大模型，昨天运行也是正常开启的。

**Comment by metercai** [comment]
内存检测不是新加的，上个版本就有。SWAP: 5632MB, 这个交换内存小了。提高这个交换内存的大小，让（RAM+SWAP）>40G，可以设置到60G比较合理。Windows下如何设置交换内存，可以在网上找。
