### ISSUE TITLE
[Feature Request]: 希望能支持可图和flux的其他功能。lora,inpaint,ipadapter。还有一点小建议

### ISSUE THREAD

**Issue by Windecay** [metercai/SimpleSDXL#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

改进建议

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

### Additional information

这个版本很好用！
改进建议：
1，更换预设时保持prompt输入框不变。（我修改meta_parser.py代码实现了）

get_image_number('image_number', 'Image Number', loaded_parameter_dict, results)
results.append(gr.update()) # 不更新 prompt
results.append(gr.update()) # 不更新 negative_prompt
get_list('styles', 'Styles', loaded_parameter_dict, results)
performance = get_str('performance', 'Performance', loaded_parameter_dict, results)

2，禁用NSFW功能疑似会报错。
3，顶上栏目不限制14个预设，而是根据总数动态扩展。（我改了shared.py文件实现了）

presets_folder = './presets/'

json_files_count = len([f for f in os.listdir(presets_folder) if f.endswith('.json')])

BUTTON_NUM = json_files_count

4，修改内置comfyUI的启动参数。默认开启--disable-smart-memory，这样跑完图后comfyUI不会长期占用显存。（action="store_false"）
5，Flux希望支持lora和重绘， flux-schnell完全可以替换成hyper-flux.
6，可图生态相对完善，希望支持。

**Comment by Windecay** [comment]
默认反推提示词方式我手动更改为双选，会更丰富。
default_describe_content_type = get_config_item_or_set_default(
    key='default_describe_content_type',
    default_value=[modules.flags.describe_type_photo,modules.flags.describe_type_anime],
    validator=lambda x: all(k in modules.flags.describe_types for k in x),
    expected_type=list

**Comment by metercai** [comment]
谢谢建议，几点说明：
1，在预置json里不包含prompt键值就是不更新提示框内容，negative_prompt也一样。不要改代码，不然想更新的就更新不了了。
2，模型加载错误，在排查。
3，动态预置会撑爆导航条，在找解决方案中。
4，切换预置会清楚显存占用。现在的显存占用是为了加速在同一预置下的反复出图。
5，Flux的lora和hyper-flux在测试版上可以用了，cn不成熟，inpaint好像还没有吧。
6，可图的这几个在计划中。
7，反推计划用minicpm2.6，比现在的丰富多了。

**Comment by Windecay** [comment]
动态预置我修改后用着好像没有问题，我有20个预设，没有爆掉，缩小窗口会自动生成新的一行。 minicpm好评，我在comfy也使用它。flux的inpaint是很简单的，就是普通的噪波遮罩工作流，修复能力极强。 不过flux目前outpaint不行。

**Comment by metercai** [comment]
等相对成熟再上，SimpleSDXL不求追新，做相对成熟的沉淀，高效稳定，强调一致性。与comfyui的定位有区别。

**Comment by Windecay** [comment]
第四点，fooocus和内置comfyUI的显存策略有所不同。 fooocus不需要添加--always-offload-vram命令就可以自动卸载模型到内存上待命。 但是内置的comfyUI就不会如此。目前除了手动修改cli_arg就没有办法控制这个comfy的调度策略（run.bat启动参数不对comfy生效），个人还是喜欢释放显存到内存上。或提供一个可选项？

**Comment by metercai** [comment]
你是需要默认--disable-smart-memory来启动comfyd吗？自动卸载到内存？

**Comment by Windecay** [comment]
是的没错。 我平时使用comfyUI正式版时候都默认会添加--disable-smart-memory，图片生成完毕就会自动回退内存（与fooocus默认的策略一致）。  现在我的实现方法是修改了cli_arg.py文件的一行参数让其自动生效。
文件路径".\SimpleSDXL2\SimpleSDXL\comfy\comfy\cli_args.py"
117行
parser.add_argument("--disable-smart-memory", action="store_false", help="Force ComfyUI to agressively offload to regular ram instead of keeping models in vram when it can.")
目前运行良好。
您可以测试一下方案的优劣。

**Comment by metercai** [comment]
我试试看，效果好的话自接做默认启动参数了。

你用qq吗，可以加群再私聊。

**Comment by Windecay** [comment]
好啊~我想加群我的QQ是4453636

**Comment by Windecay** [comment]
通过一段时间使用，Juggernaut-X-RunDiffusion-NSFW.safetensors的效果好像不如Juggernaut-XL-v8，而且只要是带人的图片，基本不符合“亚洲口味”。 后来我手动替换成了适合亚洲宝宝体质的LEOSAM HelloWorld 新世界v7.0。XD
