### ISSUE TITLE
[Feature Request]: Please Enable LoRAs in SDXL-Comfy Mode

### ISSUE THREAD

**Issue by DavidDragonsage** [metercai/SimpleSDXL#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Allow for the use of LoRAs when SimpleSDXL is working with the Comfy backend.

Not only would this allow for LoRA usage with the new models such as Flux, which now has LoRAs available for all the different Flux versions, but it would allow for other SimpleSDXL modules such as IC-Light to use LoRAs.

### Proposed workflow

LoRAs would not be disabled in Comfy mode, so there would be no difference in LoRA availability when selecting the Models tab in either Fooocus or Comfy mode.

### Additional information

I have been experimenting with IC-Light using an SDXL base model (IC-Light actually does run with only 4GB of VRAM in Comfy mode). Unfortunately the image is substantially altered because the original LoRAs that I used in mainline Fooocus are disabled.

**Comment by metercai** [comment]
Due to the wide variety of cases, it is a complex task that requires LoRAS enablement in the Comfy backend.

For example, the base model of IC-Light mode is sd1.5, which makes it impossible to load xl-loras.

We will unlock the loras for different cases in the future. Lora will soon be supported on Flux model.

**Comment by DavidDragonsage** [comment]
Thank you, that will be great!

Yes, I have been researching IC-Light further since I wrote this and realize the Comfy workflow is down-scaling to SD1.5 resolutions, applying IC-Light and then upscaling back to SDXL resolutions. It is understandable that SDXL LoRAs cannot be used.

**Comment by metercai** [comment]
The latest official version of 0916 supporting Flux Lora has been released.

**Comment by DavidDragonsage** [comment]
Wonderful! Thank you for all your work on this! 🎈🎉👍 

I see this version requires a new installation rather than being an auto-update. I know that is necessary at times when the changes are extensive. We had to do that with mainline Fooocus sometimes. I'll let people know!

**Comment by DavidDragonsage** [comment]
Could you recommend some LoRAs that might work with Flux1 Dev?

I tried FLUX🌟Draco Felis Style🐲
https://civitai.com/models/661872/fluxdraco-felis-style

and FLUX 🌟FaeTastic Details
https://civitai.com/models/643886/flux-faetastic-details

Neither of them use a keyword. They show up in the log properly but the output images are identical to the original created without a LoRA.

Also tried Faeothic - (Fae-Gothic-Lowbrow) - [FLUX] | DAM
https://civitai.com/models/718492/faeothic-fae-gothic-lowbrow-flux-or-dam
which uses the keyword "Faeothic", but there was no change in the output. It was logged correctly.

**Comment by DavidDragonsage** [comment]
Yes, that was the image I was trying to use! The LoRA was supposed to work with Flux1 Dev - but it did not.

I will try with the Flux🚀 preset. This is strange!

**Comment by DavidDragonsage** [comment]
I did get the FLUX🌟Draco Felis Style🐲 LoRA to work with the with Flux🚀 preset also. Not as good an image as yours (probably a different seed) but its definitely working.

**Comment by DavidDragonsage** [comment]
I think I may have found the Flux🚀 preset model, flux-hyp8-Q5_K_M.gguf, at CivitAI:
https://huggingface.co/mhnakif/flux-hyp16-gguf-k

 I also checked the hugging face page where you are downloading it from, but there was no model information there: 
https://huggingface.co/mhnakif/flux-hyp16-gguf-k

If it is the same model, the CivitAI page suggests using 16 steps but the preset is set for 12 steps. Did you find that 16 steps was not required?

I just tried the test image again - the images are attached. 16 steps seems to have more detail. I know I could just add another preset, except I am always trading off one preset for another with the current 14 preset limit. 😉

![12 Steps](https://github.com/user-attachments/assets/08e6aa97-6d32-48fe-bdde-3a4adff2b70e)

![16 Steps](https://github.com/user-attachments/assets/2e4e99c8-a086-479c-bbe5-872c500d2446)

**Comment by metercai** [comment]
> I think I may have found the Flux🚀 preset model, flux-hyp8-Q5_K_M.gguf, at CivitAI: https://huggingface.co/mhnakif/flux-hyp16-gguf-k
> 
> I also checked the hugging face page where you are downloading it from, but there was no model information there: https://huggingface.co/mhnakif/flux-hyp16-gguf-k
> 
> If it is the same model, the CivitAI page suggests using 16 steps but the preset is set for 12 steps. Did you find that 16 steps was not required?
> 
> I just tried the test image again - the images are attached. 16 steps seems to have more detail. I know I could just add another preset, except I am always trading off one preset for another with the current 14 preset limit. 😉
> 
> ![12 Steps](https://private-user-images.githubusercontent.com/162500231/368010638-08e6aa97-6d32-48fe-bdde-3a4adff2b70e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjY5ODUsIm5iZiI6MTcyNjU2NjY4NSwicGF0aCI6Ii8xNjI1MDAyMzEvMzY4MDEwNjM4LTA4ZTZhYTk3LTZkMzItNDhmZS1iZGRlLTNhNGFkZmYyYjcwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwOTUxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODU1M2NlMWJjZGJmYWU0M2JkZWI4Y2MyYzQyZmY0OWYzODJlZmU4MDQ1Y2ZhZWNhZWMwYjNhZjUyYzU2NmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k9PSxG-TB0qlVtcy1qqBNt1EsVBV_IBUxp2Hr5oR85g)
> 
> ![16 Steps](https://private-user-images.githubusercontent.com/162500231/368010670-2e4e99c8-a086-479c-bbe5-872c500d2446.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjY5ODUsIm5iZiI6MTcyNjU2NjY4NSwicGF0aCI6Ii8xNjI1MDAyMzEvMzY4MDEwNjcwLTJlNGU5OWM4LWEwODYtNDc5Yy1iYmU1LTg3MmM1MDBkMjQ0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwOTUxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODI0YjI2YTNiNTI5OWNkNDBkOTk3NjNhZDlhNWE5ZjE3M2I1YjhjMmY0NTAwMjc0ZWM0MWNlMGFmNTM3ZGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N-kwixKICfJSoODceQP3g5ovzpHimddfAc_L7QNiT0Q)

We chose hyp8, not hyp16 : https://huggingface.co/mhnakif/flux-hyp8-gguf-k/tree/main
8 steps are standard, 12 steps have better results.

**Comment by DavidDragonsage** [comment]
@metercai My apologies! I was getting quite tired when I was researching this.

The Civitai link to this model is here:
https://civitai.com/models/715925?modelVersionId=800644
This provides more information on the model, which was not available at Hugging Face.

I downloaded this file from Civitai and the file is identical to the one at Hugging Face. Mystery solved! 

Thank you very much for adding the LoRA support, I am sure the community (at least the Pure Fooocus Facebook group) will really appreciate this! ❤️
