### ISSUE TITLE
提参重生功能，如果模型文件名为中文，点击生成后会卡住

### ISSUE THREAD

**Issue by lsr1008n** [metercai/SimpleSDXL#7]
**Describe the problem**
提参重生功能，如果模型文件名为中文，点击生成后会卡住

**Full Console Log**
无日志，从模型选项卡的下拉框上是乱码

**Comment by metercai** [comment]
肯定是转码问题，能截图看看吗？ 
1，模型文件所在目录的list清单截图，用”ls -l“或”dir"
2，模型设置菜单里下拉列表的截图
3，图片对应log.html上的参数截图

**Comment by lsr1008n** [comment]
1. checkpoints目录：

**Comment by lsr1008n** [comment]
1. checkpoints目录：
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2023/7/17     12:32     4265097028 2Guofeng2_v20MIX.safetensors
-a----         2023/9/14      8:10     2299933688 3Guofeng3_v34.safetensors
-a----        2023/10/28      8:07    13857652570 4Guofeng4XL_v12.safetensors
-a----         2023/11/2     14:24     7105348560 juggernautXL_version6Rundiffusion.safetensors
-a----        2023/11/25     19:31     6938040698 leosamsHelloworldSDXL_helloworldSDXL20.safetensors
-a----         2023/12/2     16:34              0 put_checkpoints_here
-a----        2023/10/21     16:18     6938053346 realisticStockPhoto_v10.safetensors
-a----         2023/9/20     18:52     6938078334 sd_xl_base_1.0_0.9vae.safetensors
-a----         2023/9/20     18:47     6075981930 sd_xl_refiner_1.0_0.9vae.safetensors
-a----         2023/11/8     21:58    13857652570 XLGufengxl_gufengxl10.safetensors
-a----         2023/9/18     10:35     6938040682 xxmix9realisticsdxl_v10.safetensors
-a----         2023/9/14     17:49     2400040320 xxmix9realistic_v40.safetensors
-a----         2023/12/2     22:54     6938043562 墨幽人造人XL_v0.1.safetensors
-a----         2023/12/2     23:05     6938041018 时光Time胶片摄影-家叔马丁Mr_M_v1.0.safetensors
-a----         2023/12/2     23:02     6938040682 烟上月の写实摄影_十指流玉XL_v10.safetensors

2. 选择提参前和提参后的模型列表截图：
<img width="319" alt="屏幕截图 2023-12-05 130155" src="https://github.com/metercai/SimpleSDXL/assets/76503062/c171a403-cb17-4989-9a45-c3abd27ab7f2">
<img width="303" alt="屏幕截图 2023-12-05 130216" src="https://github.com/metercai/SimpleSDXL/assets/76503062/7710bdf5-5df7-42a3-bb44-fe0007c497b5">

3. log.html
![Uploading 屏幕截图 2023-12-05 130245.png…]()

**Comment by lsr1008n** [comment]
def parse_html_log(choice):
    global images_prompt
    
    choice = choice.split('/')[0]
    html_file = os.path.join(os.path.join(config.path_outputs, '20' + choice), 'log.html')
    # 这一行加上编码就可以了
    html = etree.parse(html_file, etree.HTMLParser(encoding='utf8'))

**Comment by xhoxye** [comment]
我也有类似的错误，提参重生
![QQ截图20231208080607](https://github.com/metercai/SimpleSDXL/assets/129571231/b7879d63-64ed-47f6-859f-41d9565e117f)

**Comment by metercai** [comment]
中文字符集和Fooocus V2导致的解析bug都已经修复更新，大家查验一下。
