### ISSUE TITLE
[Feature Request]: When in Flux, Please Allow for LoRA Weighting to be Increased to +-3

### ISSUE THREAD

**Issue by DavidDragonsage** [metercai/SimpleSDXL#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Raise the limit on LoRA weighting from 2 to 3. As shown in the attachment, weighting is currently limited to 2. If you type in "3" the value will automatically be reduced to 2.

![Max LoRA Weight 2](https://github.com/user-attachments/assets/a787f30c-61e3-4fd2-987c-db6bfc26be6c)

### Proposed workflow

1. Increase the maximum allowed LoRA weighting to 3.
2. Press ....
3. ...

### Additional information

Please see this LoRA for an example that has workable range of at least plus or minus 3.
https://civitai.com/models/675581/anti-blur-flux-lora

**Comment by metercai** [comment]
You can modify the maximum and minimum values of Lora by yourself through config.txt. For specific instructions, please refer to the prompts in config.modification_tutorial.exe to change the config.txt
`"default_loras_min_weight": -2,`
`"default_loras_max_weight": 2,`

**Comment by DavidDragonsage** [comment]
Thank you! I see that was in mainline Fooocus too, I never noticed that before! 🙂
